### ISSUE TITLE
FastAPI : request, response 구현하기

### ISSUE THREAD

**Issue by namgyu-youn** [Team-GORANI/Side-Project#11]
## Background
- Current file tree structure
```
backend
 ┣ 📂model # model config
 ┃ ┣ 📜__init__.py
 ┃ ┗ 📜dataset.py
 ┣ 📜__init__.py
 ┣ 📜api.py # API endpoint 정의 파일
 ┣ 📜config.py
 ┣ 📜database.py
 ┣ 📜dependencies.py  # 앱 의존성 관련 로직 파일
 ┗ 📜main.py
```
- 구현 예상도는 아래와 같습니다. 부족한 기능이 있다면 댓글로 알려주세요!
![image](https://github.com/user-attachments/assets/ea10c682-e7fb-4bc0-ba77-8fa7766747db)

## To-do
- [ ] Request validation 기능 추가하기
- [x] DB(annotations) SQL로 변환하기
- [x] api.py 완성하기
- [x] main.py 완성하기
- [x] model 폴더 완성하기 (이미 구현된 Yolo 참고)

## See also
- [Produc Serving 실습 코드](https://github.com/zzsza/Boostcamp-AI-Tech-Product-Serving/tree/main)
- Product Serving 과제-2 : FastAPI

**Comment by namgyu-youn** [comment]
SQL로 변환된 메타 데이터는 아래와 같습니다. 모델  관련된 코드를 수정할 때 참고해주세요
![image](https://github.com/user-attachments/assets/e176531d-c360-41f2-99e5-a02b9d09680c)
