### ISSUE TITLE
[Frontend] Reflex 학습 및 구현하기

### ISSUE THREAD

**Issue by namgyu-youn** [Team-GORANI/Side-Project#8]
## Background - [Reflex](https://github.com/reflex-dev)
**1. Introduction**
- Python 기반의 front-end tool을 알아보던 중 알게 된 도구 -> JS같은 언어 필요 없음
- Full-stack framework : front-end(react 기반) + back-end(**FastAPI**)

**2. Pros(장점)**
- Template 존재 : 이미 Reflex를 활용한 다양한 프로젝트가 있어서 양식을 참고하기 좋다.
-  UI 구현 : gradio의 한계를 극복함. (Image 등 첨부가 자유롭다)
- 실시간 UI 수정 가능 : 코드를 수정하면 web-server UI가 바로 수정되는 구조
- Deployment : Web-server 뿐만 아니라 mobile-app으로도 배포가 가능하다. (활용도 높음)

## Todo
- [x] Step1. Reflex 학습 : 어떻게 UI를 구현하는지
- [x] Step2. Reflex를 활용한 web serving : 기본 framework 구현
- [x] Step3. 구현된 framework에서 style 변경
- [ ] Step4. FastAPI를 활용해 완성된 framework 설계하기
- [ ] (Optional) Reflex를 활용한 mobile-app serving

## See also
- [Reflex docs](https://reflex.dev/)
- [Replicate : Image Generator using reflex](https://github.com/reflex-dev/templates/tree/main/ai_image_gen)
-

**Comment by namgyu-youn** [comment]
- [Stable Diffusion template](https://reflex.dev/templates/ai_image_gen/)
- 예상 UI :Checkbox를 이용해 나무/집/사람 선택 + Image input
![image](https://github.com/user-attachments/assets/f40b5e67-d81f-4d45-9be0-609ae17109d7)

**Comment by Namgyu-Youn** [comment]
Stable Diffusion template : https://reflex.dev/templates/ai_image_gen/

**Comment by Namgyu-Youn** [comment]
![image](https://github.com/user-attachments/assets/90d31d55-cdee-4516-a2e3-f596df291c7b)
- 간단한 UI test 완료
- 위의 template처럼 UI 다듬는 것이 최종 목표
